baseURL = 'https://johnsonko.github.io/jk-travel/'
languageCode = 'zh-tw'
title = 'JK Travel | 旅遊住宿推薦'
theme = 'PaperMod'
buildFuture = true
[pagination]
  pagerSize = 10

[params]
  env = "production"
  description = "精選全球飯店住宿推薦，含即時房價與訂房連結"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = false
  ShowToc = true

[params.analytics.google]
  SiteVerificationTag = "G-C1W4X2Z4CZ"

[services.googleAnalytics]
  ID = "G-C1W4X2Z4CZ"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
